//
// Created by iacopo on 19/10/16.
//

#ifndef KERNELIMAGEPROCESSING_KERNELIMAGEGUIAPP_H
#define KERNELIMAGEPROCESSING_KERNELIMAGEGUIAPP_H


class KernelImageGUiApp {

};


#endif //KERNELIMAGEPROCESSING_KERNELIMAGEGUIAPP_H
