//
// Created by iacopo on 19/10/16.
//

#ifndef KERNELIMAGEPROCESSING_KERNELIMAGEGUIMAIN_H
#define KERNELIMAGEPROCESSING_KERNELIMAGEGUIMAIN_H


class KernelImageGUiMain {

};


#endif //KERNELIMAGEPROCESSING_KERNELIMAGEGUIMAIN_H
